name: Send WhatsApp Message

on:
  schedule:
    - cron: '40 08 * * 1-5'  # 15:00 PM IST
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Generate stock prediction
        run: python scripts/daily_moving_avg_app.py static/symbol_list_20250621.csv static
    
      - name: Send WhatsApp message
        run: python scripts/send_whatsapp.py
        env:
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          FROM_WHATSAPP_NO: ${{ secrets.FROM_WHATSAPP_NO }}
          TO_WHATSAPP_NO: ${{ secrets.TO_WHATSAPP_NO }}
